services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: scraper
    image: tmed-portal-scraper
    volumes:
      - ./data:/app/data
      - tmed-portal-data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - tmed-portal-network

  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: webhook
    image: tmed-portal-webhook
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - tmed-portal-network

networks:
  tmed-portal-network:
    name: tmed-portal-network
    driver: bridge

volumes:
  tmed-portal-data:
