services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: scraper
    image: tmed-portal-scraper
    volumes:
      - ./src:/app/src
      - tmed-scraping-data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - tmed-scraping-network

  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: webhook
    image: tmed-portal-webhook
    volumes:
      - ./src:/app/src
      - tmed-scraping-data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - tmed-scraping-network

networks:
  tmed-scraping-network:
    name: tmed-scraping-network
    driver: bridge

volumes:
  tmed-scraping-data:
