name = "tmed-portal-scraping"
main = "src/index.ts"
compatibility_date = "2024-11-19"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "tmed-portal-scraping"
database_id = "00000000-0000-0000-0000-000000000000"
preview_database_id = "11111111-1111-1111-1111-111111111111"
migrations_dir = "migrations"
